Update build_push.yaml

diff --git a/.github/workflows/build_push.yaml b/.github/workflows/build_push.yaml
--- a/.github/workflows/build_push.yaml
+++ b/.github/workflows/build_push.yaml
@@ -55,6 +55,18 @@ jobs:
       run: |
         aws ecr create-repository --repository-name ${{ secrets.RESPOSITORY_NAME }} --region ${{ secrets.AWS_REGION }}
 
+    - name: Check if a basic python Image Exists in ECR
+      id: check_image
+      run: |
+        aws ecr describe-images --repository-name ${{ secrets.ECR_REPOSITORY }} --image-ids imageTag=python-3.11 --region ${{ secrets.AWS_REGION }} || echo "Image not found"
+
+    - name: Pull, Tag, and Push if Image Not Found
+      if: steps.check_image.outputs.image_exists == 'false'
+      run: |
+        docker pull python:3.11
+        docker tag python:3.11 ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:python-3.11
+        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:python-3.11
+
     - name: Build, tag, and push image to Amazon ECR
       env:
         ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
